#ifndef ARGON_RENDERING_TARGETS_HPP
#define ARGON_RENDERING_TARGETS_HPP

#include <argon/global_config.h>
#include <argon/osal/targets.h>

#if(ARGON_PLATFORM_OS == ARGON_PLATFORM_OS_VALUE_WINDOWS)
	#define ARGON_RENDERING_BACKEND ARGON_PLATFORM_RENDERING_BACKEND_WINDOWS
#elif(ARGON_PLATFORM_OS == ARGON_PLATFORM_OS_VALUE_MACOSX)
	#define ARGON_RENDERING_BACKEND ARGON_PLATFORM_RENDERING_BACKEND_MACOSX
#elif(ARGON_PLATFORM_OS == ARGON_PLATFORM_OS_VALUE_LINUX)
	#define ARGON_RENDERING_BACKEND ARGON_PLATFORM_RENDERING_BACKEND_LINUX
#else
	#define ARGON_RENDERING_BACKEND ARGON_RENDERING_BACKEND_DUMMY
#endif

#if(ARGON_RENDERING_BACKEND == ARGON_RENDERING_BACKEND_OPENGL)
#include <argon/rendering/backends/opengl/opengl.hpp>
#endif

#endif
