#ifndef ARGON_OSAL_TARGETS_H
#define ARGON_OSAL_TARGETS_H

#define ARGON_PLATFORM_OS_VALUE_WINDOWS 1
#define ARGON_PLATFORM_OS_VALUE_MACOSX 2
#define ARGON_PLATFORM_OS_VALUE_IOS 3
#define ARGON_PLATFORM_OS_VALUE_LINUX 4

#define ARGON_PLATFORM_OS_IOS_RUNMODE_IPHONESIMULATOR 1
#define ARGON_PLATFORM_OS_IOS_RUNMODE_HARDWARE 2

#ifdef _WIN32
	#define ARGON_PLATFORM_OS ARGON_PLATFORM_OS_VALUE_WINDOWS
	#ifdef _WIN64
		#define ARGON_PLATFORM_OS_BITWIDTH 64
	#else
		#define ARGON_PLATFORM_OS_BITWIDTH 32
	#endif
	#include <argon/osal/platforms/windows/windows.h>
#endif

#if defined(__APPLE__) && defined(__MACH__)
	#include <TargetConditionals.h>
	#if TARGET_IPHONE_SIMULATOR == 1
		#define ARGON_PLATFORM_OS ARGON_PLATFORM_OS_VALUE_IOS
		#define ARGON_PLATFORM_OS_RUNMODE ARGON_PLATFORM_OS_IOS_RUNMODE_IPHONESIMULATOR
	#elif TARGET_OS_IPHONE == 1
		#define ARGON_PLATFORM_OS ARGON_PLATFORM_OS_VALUE_IOS
		#define ARGON_PLATFORM_OS_RUNMODE ARGON_PLATFORM_OS_IOS_RUNMODE_HARDWARE
	#elif TARGET_OS_MAC == 1
		#define ARGON_PLATFORM_OS ARGON_PLATFORM_OS_VALUE_MACOSX
	#endif
#endif

#if defined(__linux__)
	#define ARGON_PLATFORM_OS ARGON_PLATFORM_OS_VALUE_LINUX
	#include <argon/osal/platforms/linux/linux.h>
#endif

#endif
